## Copyright (c) 2022, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Implement a SIEM System in Splunk Using Logs Streamed from OCI"
stackDescription: "Implement a SIEM System in Splunk Using Logs Streamed from Oracle Cloud in Oracle Cloud Infrastructure."
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - release
  - availability_domain_number
  - use_existing_vcn
  - vcn_id
  - lb_subnet_id
  - compute_subnet_id

- title: Required Configuration
  visible: true  
  variables:
  - compartment_ocid
  - availability_domain_name
  - numberOfNodes
  - show_advanced

- title: Load Balancer Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - lb_shape 
  - flex_lb_min_shape
  - flex_lb_max_shape 
  - lb_listener_port
  - lb_listener_backend_port

- title: Network Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - igw_display_name
  - vcn01_cidr_block
  - vcn01_lb_subnet_cidr_block
  - vcn01_compute_subnet_cidr_block

- title: Compute Instances Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - ssh_public_key
  - InstanceShape
  - InstanceFlexShapeOCPUS
  - InstanceFlexShapeMemory
  - instance_os
  - linux_os_version

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  igw_display_name:
    type: string
    title: "IGW Display Name"
    description: "Internet Gateway display name"

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visible: true
    title: Compartment
    description: "Compartment where you want to create the solution resources"

  region:
    type: oci:identity:region:name
    required: true
    visible: true
    title: Region
    description: "Region where you want to deploy the resources defined by this stack."

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visible: true
    title: "Availability Domain to be chosen"
    description: "Availability Domain to be chosen"
    dependsOn:
      compartmentId: ${compartment_ocid}

  numberOfNodes:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "How many Webserver Nodes?"
    description: "Choose number of Webserver Nodes to be deployed."

  # Optional Configuration  
  
  lb_shape:
    type: enum
    title: "LoadBalancer Shape"
    description: "Choose LoadBalancer Shape"
    default: "flexible"
    required: false 
    enum:
      - "flexible"
      - "100Mbps"
      - "10Mbps"
      - "10Mbps-Micro"
      - "400Mbps"
      - "8000Mbps"

  flex_lb_min_shape:
    type: enum
    required: false
    default: "10"
    title: "LB Flex Min Shape"
    description: "Choose Minimum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  flex_lb_max_shape:
    type: enum
    required: false
    default: "100"
    title: "LB Flex Max Shape"
    description: "Choose Maximum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  lb_listener_port:
    type: number
    required: false
    minimum: 1
    maximum: 65535
    multipleOf: 1
    default: 80
    title: "LB Listener Port"
    description: "Choose number for Load Balancer Listener Port."

  lb_listener_backend_port:
    type: number
    required: false
    minimum: 1
    maximum: 65535
    multipleOf: 1
    default: 8080
    title: "LB Backend Port"
    description: "Choose number for Load Balancer Backend Port."

  vcn01_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR Block"
    description: "Choose CIDR block for your VCN."
    default: "10.0.0.0/16"

  vcn01_lb_subnet_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Load Balancer Public Subnet CIDR Block"
    description: "Choose CIDR block for your Load Balancer Public Subnet."
    default: "10.0.1.0/24"

  vcn01_compute_subnet_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Webserver Hosts Subnet CIDR Block"
    description: "Choose CIDR block for your Webserver Subnet."
    default: "10.0.2.0/24"

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Public SSH Key"
    description: "Choose public SSH Key to be uploaded into compute instances."
    required: false
    
  InstanceShape:
    type: oci:core:instanceshape:name
    required: false
    title: "Instance Shape"
    description: "A shape is a template that determines the number of CPUs, amount of memory, and other resources allocated to a newly created instance."
    default: "VM.Standard.E3.Flex"
    dependsOn:
      compartmentId: ${compartment_ocid}

  InstanceFlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - InstanceShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - InstanceShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - InstanceShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - InstanceShape 
            - "VM.Optimized3.Flex"

  InstanceFlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 6
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - InstanceShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - InstanceShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - InstanceShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - InstanceShape 
            - "VM.Optimized3.Flex"

  instance_os:
    type: enum
    required: false
    title: "Instance OS"
    description: "An Operating System that determines the operating system for the instance."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for the instance."
    enum:
      - "9"
      - "8"

  release:
    type: string
    required: false
    visible: false
    title: "Reference Architecture Release (OCI Architecture Center)"

outputs:

  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: copyableString
    visible: true

